apiVersion: v1
kind: Service
metadata:
  name: gan-backend-service
  labels:
    type: backend-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    type: inference-server
  
    